age_keys:
  # System-level secrets on various hosts
  - &panza age15c0a468t76uw2su43y4c7cmryjn3lt36r0p2fc5vmpmzm322aymq4ntcm6
  - &potato age1dmcrmq23arugj8h8zlr663v6hqfp58apj90ynarahl2w56jlfcdqfnsue4
  - &claudius age16pjf7q48cjrzxgt53w5lyrld7k28rckqshj3nwpnfprgdfyhhg3sxcsl0a
  - &napoleon age1ktg5a2hchfng6x96tj0chskvdyr99flu3u862kv9yege93cxfeksfy3pdd
  - &sebastiao age1vucd8rp4s96hx4jq23mmxy6j8s3pdjttdfpzes072aeyjs82tgdszhqey9
  # User master encryption keys
  - &kerry_master age1xvyp63kuszp4u0ke4lf84wstgt6td04v6w605twh3mwqaedv9u8sdm8g4j
creation_rules:
  - path_regex: (^|/)(napoleon/secrets|secrets/napoleon)(/.+|\.[^/]+)$
    key_groups:
      - age:
        - *napoleon
        - *kerry_master
  - path_regex: (^|/)(panza/secrets|secrets/panza)(/.+|\.[^/]+)$
    key_groups:
      - age:
        - *panza
        - *kerry_master
  - path_regex: (^|/)(potato/secrets|secrets/potato)(/.+|\.[^/]+)$
    key_groups:
      - age:
        - *potato
        - *kerry_master
  - path_regex: (^|/)(claudius/secrets|secrets/claudius)(/.+|\.[^/]+)$
    key_groups:
      - age:
        - *kerry_master
        - *claudius
  - path_regex: (^|/)(sebastiao/secrets|secrets/sebastiao)(/.+|\.[^/]+)$
    key_groups:
      - age:
        - *kerry_master
        - *sebastiao
  - path_regex: ^modules/mcp/servers/secrets/.+
    key_groups:
      - age:
        - *kerry_master
        - *claudius
        - *napoleon
        - *panza
        - *potato
        - *sebastiao
  - path_regex: ^modules/users/kerry/secrets/hashed-password$
    key_groups:
      - age:
        - *kerry_master
        - *claudius
        - *napoleon
        - *panza
        - *potato
        - *sebastiao
