{
  imports = [
    ./common/bat
    ./common/easyeffects.nix
    ./common/eza
    ./common/fish
    ./common/kitty.nix
    ./common/libreoffice.nix
    ./common/moor
    ./common/nvim
    ./common/nvim/lazynixcompat.nix
    ./common/oh-my-posh
    ./common/ssh.nix
    ./common/shell.nix
    ./common/shell-utils
    ./common/vscode.nix
    ./common/zathura
    ./common/zsh
    ./users/erika
    ./users/julie
    ./users/kerry
  ];
}
